# Generated by Django 2.2.2 on 2019-10-29 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cddd_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testDB',
        ),
    ]
